- hosts: web-server
  remote_user: ubuntu
  become: true
  #become_method: sudo
  vars_files:
    - var/secret


  tasks:
    - name: Update all packages
      apt:
        update_cache: yes
        name: "*"
        state: latest

    - name: Install dependencies
      apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - htop
          - git
          - python3-pip
          - python3-setuptools


    - name: Install apt key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present
        keyring: /etc/apt/trusted.gpg.d/docker.gpg

    - name: Install docker repo
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker


    - name: install docker
      apt:
        update_cache: yes
        pkg:
          - docker-ce
          #- docker-ce-cli
          #- containerd.io
          #- docker-compose-plugin

    - name: adding existing user "ubuntu" to group docker
      user:
        name: "ubuntu"
        groups: docker
        append: yes

    - name: Install docker-compose from official github repo
      get_url:
        url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '775'

    - name: install 'Docker SDK for Python'
      pip:
        name:
          - docker
          - docker-compose


    - name: Upload SSH key
      copy:
        src: "{{ git_key }}"
        dest: ~/.ssh
        mode: "0600"
        force: yes


#REpository
    - name: Clone a Github repo
      git:
        repo: https://github.com/akril1k/test-api
        dest: /home/test-api
        clone: yes
        update: yes

    - name: Write env files
      become: yes
      copy:
        src: "{{ env_file }}"
        dest: /home/test-api/.env

    - name: Write key.env files
      copy:
        src: "{{ key_file }}"
        dest: /home/test-api/key.env

#UP app
    - name: Run `docker-compose up`
      community.docker.docker_compose:
        state: present
        project_src: "/home/test-api/"
